/**
 * Сгенерировано `node Seedlings/scripts/photo-manifest.mjs` — вручную не править.
 * Ключ — слаг сорта, значение — пути к файлам в /public/photos.
 */
export const PHOTOS: Record<string, string[]> = {
  "ezhevika-karaka-blek": ["/photos/ezhevika-karaka-blek.jpg"],
  "ezhevika-voshito": ["/photos/ezhevika-voshito.jpg"],
  "golubika-blyukrop": ["/photos/golubika-blyukrop.jpg"],
  "golubika-dyuk": ["/photos/golubika-dyuk.jpg"],
  "golubika-sierra": ["/photos/golubika-sierra.jpg"],
  "klubnika-frigo-kleri": ["/photos/klubnika-frigo-kleri.jpg"],
  "klubnika-frigo-malvina": ["/photos/klubnika-frigo-malvina.jpg"],
  "klubnika-zks-aprika": ["/photos/klubnika-zks-aprika.jpg"],
  "klubnika-zks-primi": ["/photos/klubnika-zks-primi.jpg"],
  "malina-letnyaya-glen-ampl": ["/photos/malina-letnyaya-glen-ampl.jpg"],
  "malina-letnyaya-gusar": ["/photos/malina-letnyaya-gusar.jpg"],
  "malina-letnyaya-lyachka": ["/photos/malina-letnyaya-lyachka.jpg"],
  "malina-letnyaya-oktaviya": ["/photos/malina-letnyaya-oktaviya.jpg"],
  "malina-letnyaya-pshehiba": ["/photos/malina-letnyaya-pshehiba.jpg"],
  "malina-letnyaya-radzieva": ["/photos/malina-letnyaya-radzieva.jpg"],
  "malina-letnyaya-sokolitsa": ["/photos/malina-letnyaya-sokolitsa.jpg"],
  "malina-remontantnaya-avrora": ["/photos/malina-remontantnaya-avrora.jpg"],
  "malina-remontantnaya-dzhoan-dzhey": ["/photos/malina-remontantnaya-dzhoan-dzhey.jpg"],
  "malina-remontantnaya-enrosandira": ["/photos/malina-remontantnaya-enrosandira.jpg"],
  "malina-remontantnaya-gerakl": ["/photos/malina-remontantnaya-gerakl.jpg"],
  "malina-remontantnaya-karamelka": ["/photos/malina-remontantnaya-karamelka.jpg"],
  "malina-remontantnaya-mopema": ["/photos/malina-remontantnaya-mopema.jpg"],
  "malina-remontantnaya-nizhegorodets": ["/photos/malina-remontantnaya-nizhegorodets.jpg"],
  "malina-remontantnaya-poemat": ["/photos/malina-remontantnaya-poemat.jpg"],
  "malina-remontantnaya-polana": ["/photos/malina-remontantnaya-polana.jpg"],
  "malina-remontantnaya-polka": ["/photos/malina-remontantnaya-polka.jpg"],
  "malina-remontantnaya-primalba": ["/photos/malina-remontantnaya-primalba.jpg"],
  "malina-remontantnaya-yana": ["/photos/malina-remontantnaya-yana.jpg"],
  "malina-remontantnaya-zyugana": ["/photos/malina-remontantnaya-zyugana.jpg"],
  "smorodina-zks-belorusskaya-sladkaya": ["/photos/smorodina-zks-belorusskaya-sladkaya.jpg"],
  "smorodina-zks-ben-houpen": ["/photos/smorodina-zks-ben-houpen.jpg"],
  "smorodina-zks-klaussonovskaya": ["/photos/smorodina-zks-klaussonovskaya.jpg"],
  "smorodina-zks-ruben": ["/photos/smorodina-zks-ruben.jpg"],
  "smorodina-zks-titaniya": ["/photos/smorodina-zks-titaniya.jpg"],
};
